### ISSUE TITLE
[Little Bug] Last line changed ?

### ISSUE THREAD

**Issue by acaruso-syn** [GitFiend/Support#134] opened 2022-08-29 08:27 UTC
When editing files I noticed that the commit section always shows the last line of the file as if I added it in addition to my changes. I haven't tried what happens if I don't push the line and don't want to find out, but it sounds like a bug. I share an image to make the idea. The last line was neither added nor changed. The same behavior happens if I select the first file. (All on Intel Mac with GitFiend version 0.36)
<img width="750" alt="Schermata 2022-08-29 alle 09 50 11" src="https://user-images.githubusercontent.com/95630485/187157964-2291cb53-863d-406b-8252-ebca7cdb85a8.png">

**Comment by GitFiend** [comment] 2022-10-12 00:25
I've found the cause and have a fix for this coming soon.

**Closed** 2022-10-19 09:20 UTC
