### ISSUE TITLE
Where is master?

### ISSUE THREAD

**Issue by mikepc** [GitFiend/Support#2] opened 2019-06-24 20:44 UTC
The master branch is entirely inaccessible for me :(

![Screen Shot 2019-06-24 at 1 43 30 PM](https://user-images.githubusercontent.com/878739/60050697-1a261c00-9686-11e9-9815-ade46965d6e0.png)

When I "show all branches" master does not appear, nor anywhere else in the app.

**Comment by mikepc** [comment] 2019-06-24 20:48
A separate project loaded master, but this one .. no dice :(

**Comment by tsuggate** [comment] 2019-06-24 22:04
That's interesting. Any chance you have a repo I could check out to reproduce the issue?

Does this repo have multiple remotes?

**Comment by mikepc** [comment] 2019-06-24 23:22
this is on a private gitlab enterprise server, I will see if I can
replicate it on a side project

**Comment by GitFiend** [comment] 2019-06-25 10:20
Thanks for taking the time to enter a bug. 

Going by the picture, it seems there are a lot of commits missing also? Is that true? Do you see any red error boxes when you load the repo? 

One reason why you may not see master is if your repo has more than one remote URL, but it looks like there's more going on here.

**Comment by mikepc** [comment] 2019-06-25 15:07
I don't know about missing commits, but there are several remotes!

**Comment by markalzate13** [comment] 2019-08-29 00:48
Don’t worry people I don’t burn what people benefit from, I just don’t like how people don’t respect masters legacy, people benefit from me but people don’t even appreciate what they retain and what makes there apps and programs much better and reliable.

**Comment by GitFiend** [comment] 2019-08-29 09:23
Closing this as there are no reproduce steps, I've been unable to reproduce it and there have been no other reports of it happening.

**Closed by GitFiend** 2019-08-29 09:23 UTC
